[package]
name = "relibc"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "c"
crate-type = ["staticlib"]

[workspace]
members = ["src/crt0"]

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins.git", default-features = false, features = ["mem"] }
ctype = { path = "src/ctype" }
errno = { path = "src/errno" }
fcntl = { path = "src/fcntl" }
fenv = { path = "src/fenv" }
float = { path = "src/float" }
grp = { path = "src/grp" }
mman = { path = "src/mman" }
platform = { path = "src/platform" }
resource = { path = "src/resource" }
semaphore = { path = "src/semaphore" }
stat = { path = "src/stat" }
stdio = { path = "src/stdio" }
stdlib = { path = "src/stdlib" }
string = { path = "src/string" }
sys_time = { path = "src/sys_time" }
time = { path = "src/time" }
unistd = { path = "src/unistd" }
wait = { path = "src/wait" }
wctype = { path = "src/wctype" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
